# $Id: //depot/google3/googledata/corp/puppet/goobuntu/common/modules/shell/files/bash/skel.bashrc#11 $
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
if [[ $TERM == *color ]]; then
    color_prompt=yes
fi

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\][\033[00m\]:cTop\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    #PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
    PS1='${debian_chroot:+($debian_chroot)}:cTop\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*|screen.xterm*|screen.rxvt*)
    #PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}:cTop\w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias diff='diff --color=auto'
fi


alias listalias='cat $HOME/bin/exe/aliaslist'

# some more ls aliases
bu () { cp ~/.bashrc ~/bin/.backup/'bashrc'-`date +%Y%m%d%H%M`.backup ;  }
alias bashme='vi $HOME/.bashrc'
alias editbash='bu && bashme'
alias s='source $HOME/.bashrc'

alias gocert='gcert'
alias lall='ls -alh'                        # List files
alias lsize='ls -alhSr'                      # List files by size
alias ldate='ls -alhtr'                      # List files by date

h() { history | grep "$1"; }              # Shorthand for `history` with added grepping
dirsize ()
{
du -shx * .[a-zA-Z0-9_]* 2> /dev/null | \
egrep '^ *[0-9.]*[MG]' | sort -n > /tmp/list
egrep '^ *[0-9.]*M' /tmp/list
egrep '^ *[0-9.]*G' /tmp/list
rm -rf /tmp/list
}
 
# A helper function to help SSH to cloud machines.
# Use: cloudssh <myproject>
# Example: cloudssh cloudacrolinx-dev
function cloudssh() {
  if [[  $1 == "" ]]; then echo "provide the project name -> cloudssh <myproject>" ; return; fi
  machines=( $( gcloud compute instances list --project "$1" --uri | sed 's#^https://www.googleapis.com/compute/v1/projects/\(.*\)/zones/\(.*\)/instances/\(.*\)$#nic0.\3.\2.c.\1.internal.gcpnode.com#' ))
  if [[  $machines == "" ]]; then return; fi
  for m in "${!machines[@]}"; do echo "$m)" "${machines[$m]}"; done
  echo -n "Choose machine #"
  read select
  # If no selection (like extraneous "enter"), bail out.
  if [[  $select == "" ]]; then echo "no selection, exiting"; return; fi
  if [[  $2 == "" ]]; then
    echo ssh "${machines[$select]}"
    ssh  "${machines[$select]}"
  else
    echo ssh "${2}@${machines[$select]}"
    ssh "${2}@${machines[$select]}"
  fi
}
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

